name: Flutter Web
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./flutter_intl_with_flutter_bloc_example
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
        
    - name: Enable Flutter web 
      run: flutter config --enable-web
      working-directory: ${{ env.working-directory }}
      
    - name: Install dependencies
      run: flutter packages get
      working-directory: ${{ env.working-directory }}
      
    - name: Build web
      run: flutter build web
      working-directory: ${{ env.working-directory }}
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./flutter_intl_with_flutter_bloc_example/build/web